export interface Creator {
  id: string
  handle: string
  displayName: string
  platform: "instagram" | "tiktok"
  followers: number
  country: string
  flag: string
  countryName: string
  category: string
  rating: number
  reviewCount: number
  verified: boolean
  isLive: boolean
  viewers?: number
  avatar: string
}

export interface Auction {
  id: string
  title: string
  titleAr: string
  title_ar: string
  category: string
  categorySlug: string
  creator: Creator
  platform: "instagram" | "tiktok"
  imageUrl: string
  images: string[]
  isLive: boolean
  viewers?: number
  timeLeft?: string
  currentBid: number
  startingPrice: number
  currency: "KWD"
  status: "active" | "ending_soon" | "completed"
  endTime: Date
  bidsCount: number
  condition: string
  location: string
  description: string
  sellerName: string
  sellerRating: number
  sellerSales: number
}

export interface Category {
  id: string
  name: string
  name_ar: string
  icon: string
  slug: string
  count: number
  color: string
}

export interface BidHistory {
  id: string
  auctionId: string
  bidderName: string
  bidderAvatar: string
  amount: number
  createdAt: Date
}

export const creators: Creator[] = [
  {
    id: "c1",
    handle: "@carauctions",
    displayName: "Car Auctions Live",
    platform: "instagram",
    followers: 512000,
    country: "US",
    flag: "🇺🇸",
    countryName: "United States",
    category: "Cars",
    rating: 4.9,
    reviewCount: 1240,
    verified: true,
    isLive: true,
    viewers: 12400,
    avatar: "https://picsum.photos/seed/c1/200/200",
  },
  {
    id: "c2",
    handle: "@watch.dealer",
    displayName: "Watch Dealer",
    platform: "tiktok",
    followers: 334000,
    country: "CH",
    flag: "🇨🇭",
    countryName: "Switzerland",
    category: "Watches",
    rating: 4.8,
    reviewCount: 890,
    verified: true,
    isLive: true,
    viewers: 8700,
    avatar: "https://picsum.photos/seed/c2/200/200",
  },
  {
    id: "c3",
    handle: "@kickz.live",
    displayName: "Kickz Live",
    platform: "instagram",
    followers: 245000,
    country: "GB",
    flag: "🇬🇧",
    countryName: "United Kingdom",
    category: "Sneakers",
    rating: 4.7,
    reviewCount: 620,
    verified: true,
    isLive: true,
    viewers: 5300,
    avatar: "https://picsum.photos/seed/c3/200/200",
  },
  {
    id: "c4",
    handle: "@luxury.time",
    displayName: "Luxury Time",
    platform: "tiktok",
    followers: 185000,
    country: "AE",
    flag: "🇦🇪",
    countryName: "UAE",
    category: "Watches",
    rating: 4.9,
    reviewCount: 430,
    verified: true,
    isLive: false,
    avatar: "https://picsum.photos/seed/c4/200/200",
  },
  {
    id: "c5",
    handle: "@cars.vip",
    displayName: "Cars VIP",
    platform: "instagram",
    followers: 512000,
    country: "SA",
    flag: "🇸🇦",
    countryName: "Saudi Arabia",
    category: "Cars",
    rating: 4.9,
    reviewCount: 980,
    verified: true,
    isLive: true,
    viewers: 9100,
    avatar: "https://picsum.photos/seed/c5/200/200",
  },
  {
    id: "c6",
    handle: "@estate.auctions",
    displayName: "Estate Auctions",
    platform: "instagram",
    followers: 98000,
    country: "AE",
    flag: "🇦🇪",
    countryName: "UAE",
    category: "Real Estate",
    rating: 4.6,
    reviewCount: 210,
    verified: false,
    isLive: true,
    viewers: 6200,
    avatar: "https://picsum.photos/seed/c6/200/200",
  },
  {
    id: "c7",
    handle: "@tech.auctions",
    displayName: "Tech Auctions KW",
    platform: "tiktok",
    followers: 210000,
    country: "KW",
    flag: "🇰🇼",
    countryName: "Kuwait",
    category: "Electronics",
    rating: 4.7,
    reviewCount: 340,
    verified: true,
    isLive: false,
    avatar: "https://picsum.photos/seed/c7/200/200",
  },
  {
    id: "c8",
    handle: "@collectibles.hub",
    displayName: "Collectibles Hub",
    platform: "tiktok",
    followers: 145000,
    country: "US",
    flag: "🇺🇸",
    countryName: "United States",
    category: "Gaming Collectibles",
    rating: 4.5,
    reviewCount: 180,
    verified: false,
    isLive: true,
    viewers: 4300,
    avatar: "https://picsum.photos/seed/c8/200/200",
  },
]

export const categories: Category[] = [
  { id: "cat1", name: "Cars", name_ar: "سيارات", icon: "🚗", slug: "cars", count: 142, color: "#EF4444" },
  { id: "cat2", name: "Watches", name_ar: "ساعات", icon: "⌚", slug: "watches", count: 98, color: "#F59E0B" },
  { id: "cat3", name: "Electronics", name_ar: "إلكترونيات", icon: "📱", slug: "electronics", count: 76, color: "#3B82F6" },
  { id: "cat4", name: "Sneakers", name_ar: "أحذية رياضية", icon: "👟", slug: "sneakers", count: 54, color: "#8B5CF6" },
  { id: "cat5", name: "Luxury Items", name_ar: "مقتنيات فاخرة", icon: "💎", slug: "luxury-items", count: 38, color: "#EC4899" },
  { id: "cat6", name: "Real Estate", name_ar: "عقارات", icon: "🏢", slug: "real-estate", count: 22, color: "#10B981" },
  { id: "cat7", name: "Gaming Collectibles", name_ar: "مقتنيات الألعاب", icon: "🃏", slug: "gaming-collectibles", count: 67, color: "#0B8A7E" },
]

const now = new Date()
const inMinutes = (m: number) => new Date(now.getTime() + m * 60000)

export const liveAuctions: Auction[] = [
  {
    id: "a1",
    title: "2021 Mercedes G63 AMG",
    titleAr: "مرسيدس G63 AMG 2021",
    title_ar: "مرسيدس G63 AMG 2021",
    category: "Cars",
    categorySlug: "cars",
    creator: creators[0],
    platform: "instagram",
    imageUrl: "https://picsum.photos/seed/mercedesg63/400/300",
    images: ["https://picsum.photos/seed/mercedesg63/400/300", "https://picsum.photos/seed/mercedesg63b/400/300"],
    isLive: true,
    viewers: 12400,
    timeLeft: "02:14:33",
    currentBid: 28500,
    startingPrice: 20000,
    currency: "KWD",
    status: "active",
    endTime: inMinutes(134),
    bidsCount: 47,
    condition: "Used - Excellent",
    location: "Kuwait City, Kuwait",
    description: "2021 Mercedes G63 AMG in obsidian black. Full service history, original paint, no accidents. GCC specs.",
    sellerName: "Car Auctions Live",
    sellerRating: 4.9,
    sellerSales: 234,
  },
  {
    id: "a2",
    title: "Rolex Daytona 116508",
    titleAr: "رولكس دايتونا 116508",
    title_ar: "رولكس دايتونا 116508",
    category: "Watches",
    categorySlug: "watches",
    creator: creators[1],
    platform: "tiktok",
    imageUrl: "https://picsum.photos/seed/rolexdaytona/400/300",
    images: ["https://picsum.photos/seed/rolexdaytona/400/300"],
    isLive: true,
    viewers: 8700,
    timeLeft: "00:04:12",
    currentBid: 14200,
    startingPrice: 10000,
    currency: "KWD",
    status: "ending_soon",
    endTime: inMinutes(4),
    bidsCount: 89,
    condition: "Pre-owned - Mint",
    location: "Geneva, Switzerland",
    description: "Rolex Daytona 116508 in 18k yellow gold with champagne dial. Box and papers 2020.",
    sellerName: "Watch Dealer",
    sellerRating: 4.8,
    sellerSales: 189,
  },
  {
    id: "a3",
    title: "Nike Air Jordan 1 Retro High OG",
    titleAr: "نايك اير جوردان 1 ريترو هاي",
    title_ar: "نايك اير جوردان 1 ريترو هاي",
    category: "Sneakers",
    categorySlug: "sneakers",
    creator: creators[2],
    platform: "instagram",
    imageUrl: "https://picsum.photos/seed/airjordan1/400/300",
    images: ["https://picsum.photos/seed/airjordan1/400/300"],
    isLive: true,
    viewers: 5300,
    timeLeft: "01:22:08",
    currentBid: 185,
    startingPrice: 100,
    currency: "KWD",
    status: "active",
    endTime: inMinutes(82),
    bidsCount: 23,
    condition: "New with box",
    location: "London, UK",
    description: "Nike Air Jordan 1 Retro High OG 'Chicago' - Size US 10. Brand new, deadstock. 100% authentic.",
    sellerName: "Kickz Live",
    sellerRating: 4.7,
    sellerSales: 312,
  },
  {
    id: "a4",
    title: "Patek Philippe Nautilus 5711",
    titleAr: "باتيك فيليب نوتيلوس 5711",
    title_ar: "باتيك فيليب نوتيلوس 5711",
    category: "Watches",
    categorySlug: "watches",
    creator: creators[3],
    platform: "tiktok",
    imageUrl: "https://picsum.photos/seed/pateknautil/400/300",
    images: ["https://picsum.photos/seed/pateknautil/400/300"],
    isLive: false,
    timeLeft: "12:00:00",
    currentBid: 52000,
    startingPrice: 40000,
    currency: "KWD",
    status: "active",
    endTime: inMinutes(720),
    bidsCount: 12,
    condition: "Pre-owned - Very Good",
    location: "Dubai, UAE",
    description: "Patek Philippe Nautilus 5711/1A-010 stainless steel with blue dial. Complete set with box & papers 2019.",
    sellerName: "Luxury Time",
    sellerRating: 4.9,
    sellerSales: 98,
  },
  {
    id: "a5",
    title: "BMW M4 Competition",
    titleAr: "بي إم دبليو M4 كومبيتيشن",
    title_ar: "بي إم دبليو M4 كومبيتيشن",
    category: "Cars",
    categorySlug: "cars",
    creator: creators[4],
    platform: "instagram",
    imageUrl: "https://picsum.photos/seed/bmwm4/400/300",
    images: ["https://picsum.photos/seed/bmwm4/400/300"],
    isLive: true,
    viewers: 9100,
    timeLeft: "03:45:00",
    currentBid: 9800,
    startingPrice: 7500,
    currency: "KWD",
    status: "active",
    endTime: inMinutes(225),
    bidsCount: 34,
    condition: "Used - Good",
    location: "Riyadh, Saudi Arabia",
    description: "2022 BMW M4 Competition in Frozen Portimao Blue. GCC spec, 18,000 km. First owner.",
    sellerName: "Cars VIP",
    sellerRating: 4.9,
    sellerSales: 145,
  },
  {
    id: "a6",
    title: "Yeezy Boost 350 V2 Zebra",
    titleAr: "ييزي بوست 350 V2 زيبرا",
    title_ar: "ييزي بوست 350 V2 زيبرا",
    category: "Sneakers",
    categorySlug: "sneakers",
    creator: creators[2],
    platform: "instagram",
    imageUrl: "https://picsum.photos/seed/yeezyzebra/400/300",
    images: ["https://picsum.photos/seed/yeezyzebra/400/300"],
    isLive: true,
    viewers: 3200,
    timeLeft: "00:52:18",
    currentBid: 220,
    startingPrice: 150,
    currency: "KWD",
    status: "ending_soon",
    endTime: inMinutes(52),
    bidsCount: 18,
    condition: "New with box",
    location: "London, UK",
    description: "Adidas Yeezy Boost 350 V2 Zebra. Size US 9.5. Brand new, never worn.",
    sellerName: "Kickz Live",
    sellerRating: 4.7,
    sellerSales: 312,
  },
  {
    id: "a7",
    title: "Luxury Villa Dubai Marina",
    titleAr: "فيلا فاخرة دبي مارينا",
    title_ar: "فيلا فاخرة دبي مارينا",
    category: "Real Estate",
    categorySlug: "real-estate",
    creator: creators[5],
    platform: "instagram",
    imageUrl: "https://picsum.photos/seed/dubivilla/400/300",
    images: ["https://picsum.photos/seed/dubivilla/400/300"],
    isLive: true,
    viewers: 6200,
    timeLeft: "05:30:00",
    currentBid: 450000,
    startingPrice: 380000,
    currency: "KWD",
    status: "active",
    endTime: inMinutes(330),
    bidsCount: 8,
    condition: "New",
    location: "Dubai Marina, UAE",
    description: "5-bedroom luxury villa in Dubai Marina with private pool and sea view. 700 sqm. Freehold.",
    sellerName: "Estate Auctions",
    sellerRating: 4.6,
    sellerSales: 22,
  },
  {
    id: "a8",
    title: "Pokemon Charizard PSA 10",
    titleAr: "بوكيمون شاريزارد PSA 10",
    title_ar: "بوكيمون شاريزارد PSA 10",
    category: "Gaming Collectibles",
    categorySlug: "gaming-collectibles",
    creator: creators[7],
    platform: "tiktok",
    imageUrl: "https://picsum.photos/seed/charizard/400/300",
    images: ["https://picsum.photos/seed/charizard/400/300"],
    isLive: true,
    viewers: 4300,
    timeLeft: "01:08:45",
    currentBid: 3200,
    startingPrice: 2500,
    currency: "KWD",
    status: "active",
    endTime: inMinutes(68),
    bidsCount: 56,
    condition: "PSA Graded 10",
    location: "New York, USA",
    description: "1999 Base Set Holographic Charizard graded PSA 10 Gem Mint. One of only 121 in existence at this grade.",
    sellerName: "Collectibles Hub",
    sellerRating: 4.5,
    sellerSales: 87,
  },
  {
    id: "a9",
    title: "iPhone 15 Pro Max 1TB",
    titleAr: "آيفون 15 برو ماكس 1 تيرابايت",
    title_ar: "آيفون 15 برو ماكس 1 تيرابايت",
    category: "Electronics",
    categorySlug: "electronics",
    creator: creators[6],
    platform: "tiktok",
    imageUrl: "https://picsum.photos/seed/iphone15/400/300",
    images: ["https://picsum.photos/seed/iphone15/400/300"],
    isLive: false,
    timeLeft: "06:00:00",
    currentBid: 520,
    startingPrice: 400,
    currency: "KWD",
    status: "active",
    endTime: inMinutes(360),
    bidsCount: 15,
    condition: "New sealed",
    location: "Kuwait City, Kuwait",
    description: "Apple iPhone 15 Pro Max 1TB Natural Titanium. Factory sealed, international warranty.",
    sellerName: "Tech Auctions KW",
    sellerRating: 4.7,
    sellerSales: 56,
  },
  {
    id: "a10",
    title: "2022 Tesla Model S Plaid",
    titleAr: "تسلا موديل S بلايد 2022",
    title_ar: "تسلا موديل S بلايد 2022",
    category: "Cars",
    categorySlug: "cars",
    creator: creators[0],
    platform: "instagram",
    imageUrl: "https://picsum.photos/seed/teslamodels/400/300",
    images: ["https://picsum.photos/seed/teslamodels/400/300"],
    isLive: true,
    viewers: 7800,
    timeLeft: "02:55:00",
    currentBid: 19500,
    startingPrice: 15000,
    currency: "KWD",
    status: "active",
    endTime: inMinutes(175),
    bidsCount: 28,
    condition: "Used - Excellent",
    location: "Kuwait City, Kuwait",
    description: "2022 Tesla Model S Plaid, midnight silver metallic. 12,000 km. Full self-driving capability.",
    sellerName: "Car Auctions Live",
    sellerRating: 4.9,
    sellerSales: 234,
  },
  {
    id: "a11",
    title: "Rolex Submariner Date",
    titleAr: "رولكس سبمارينر دايت",
    title_ar: "رولكس سبمارينر دايت",
    category: "Watches",
    categorySlug: "watches",
    creator: creators[1],
    platform: "tiktok",
    imageUrl: "https://picsum.photos/seed/rolexsub/400/300",
    images: ["https://picsum.photos/seed/rolexsub/400/300"],
    isLive: true,
    viewers: 5100,
    timeLeft: "00:38:22",
    currentBid: 7800,
    startingPrice: 5500,
    currency: "KWD",
    status: "ending_soon",
    endTime: inMinutes(38),
    bidsCount: 62,
    condition: "Pre-owned - Good",
    location: "Geneva, Switzerland",
    description: "Rolex Submariner Date 116610LN. Black bezel and dial. Year 2021, box and papers.",
    sellerName: "Watch Dealer",
    sellerRating: 4.8,
    sellerSales: 189,
  },
  {
    id: "a12",
    title: "Omega Speedmaster Moonwatch",
    titleAr: "أوميغا سبيدماستر مونووتش",
    title_ar: "أوميغا سبيدماستر مونووتش",
    category: "Watches",
    categorySlug: "watches",
    creator: creators[3],
    platform: "tiktok",
    imageUrl: "https://picsum.photos/seed/omegaspeed/400/300",
    images: ["https://picsum.photos/seed/omegaspeed/400/300"],
    isLive: false,
    timeLeft: "08:15:00",
    currentBid: 2100,
    startingPrice: 1500,
    currency: "KWD",
    status: "active",
    endTime: inMinutes(495),
    bidsCount: 19,
    condition: "Pre-owned - Very Good",
    location: "Dubai, UAE",
    description: "Omega Speedmaster Professional Moonwatch 311.30.42.30.01.005. Box and papers 2022.",
    sellerName: "Luxury Time",
    sellerRating: 4.9,
    sellerSales: 98,
  },
]

export const trendingAuctions: Auction[] = liveAuctions.filter(a => a.isLive).slice(0, 5)

export const mockBidHistory: BidHistory[] = [
  {
    id: "b1",
    auctionId: "a1",
    bidderName: "Ahmed Al-Rashid",
    bidderAvatar: "https://picsum.photos/seed/bidder1/40/40",
    amount: 28500,
    createdAt: new Date(Date.now() - 2 * 60000),
  },
  {
    id: "b2",
    auctionId: "a1",
    bidderName: "Sara K.",
    bidderAvatar: "https://picsum.photos/seed/bidder2/40/40",
    amount: 28000,
    createdAt: new Date(Date.now() - 8 * 60000),
  },
  {
    id: "b3",
    auctionId: "a1",
    bidderName: "Mohammed J.",
    bidderAvatar: "https://picsum.photos/seed/bidder3/40/40",
    amount: 27500,
    createdAt: new Date(Date.now() - 15 * 60000),
  },
  {
    id: "b4",
    auctionId: "a1",
    bidderName: "Fatima Al-M.",
    bidderAvatar: "https://picsum.photos/seed/bidder4/40/40",
    amount: 26800,
    createdAt: new Date(Date.now() - 28 * 60000),
  },
  {
    id: "b5",
    auctionId: "a1",
    bidderName: "Khalid S.",
    bidderAvatar: "https://picsum.photos/seed/bidder5/40/40",
    amount: 26000,
    createdAt: new Date(Date.now() - 45 * 60000),
  },
]

// Aliases
export const mockAuctions = liveAuctions
export const mockCategories = categories
